Set clang version major to fix:
[2026/2034] Building CXX object libcxx/test/tools/clang_tidy_checks/CMakeFiles/cxx-tidy.dir/hide_from_abi.cpp.o
FAILED: libcxx/test/tools/clang_tidy_checks/CMakeFiles/cxx-tidy.dir/hide_from_abi.cpp.o
/usr/bin/clang++-24 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Dcxx_tidy_EXPORTS -isystem /usr/lib/llvm-24/include -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wno-pass-failed -Wmisleading-indentation -Wctad-maybe-unsupported -fno-omit-frame-pointer -gline-tables-only -fsanitize=thread -fdiagnostics-color -ffunction-sections -fdata-sections -Xclang -fno-pch-timestamp -O3 -DNDEBUG -std=c++20 -fPIC -fno-rtti -fno-sanitize=address,hwaddress,undefined,thread,leak -fno-sanitize=memory,dataflow -MD -MT libcxx/test/tools/clang_tidy_checks/CMakeFiles/cxx-tidy.dir/hide_from_abi.cpp.o -MF libcxx/test/tools/clang_tidy_checks/CMakeFiles/cxx-tidy.dir/hide_from_abi.cpp.o.d -o libcxx/test/tools/clang_tidy_checks/CMakeFiles/cxx-tidy.dir/hide_from_abi.cpp.o -c /llvm-project/libcxx/test/tools/clang_tidy_checks/hide_from_abi.cpp
/llvm-project/libcxx/test/tools/clang_tidy_checks/hide_from_abi.cpp:14:12: fatal error: 'clang-tidy/ClangTidyModuleRegistry.h' file not found
   14 | #  include "clang-tidy/ClangTidyModuleRegistry.h"
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1.

in

 libc++ DEBUG tsan fun,fuzz
failed 7 hours ago in 3m 47s